#Isa Grace Guthrie and Ellen Kevin
import turtle
belle=turtle.Turtle()
belle.color("cyan")
belle.forward(100)
belle.right(90)
belle.color("green")
belle.forward(100)
belle.right(90)
belle.color("blue")
belle.forward(100)
belle.right(90)
belle.color("gold")
belle.forward(100)
belle.right(90)
